version: '3.2'
services:
  web:
    build: .
    container_name: vto-web
    ports:
      - "80:80"
    links:
      - db
      - cache
    env_file:
      - env
    volumes:
      - ./web:/var/www/html
  db:
    image: mariadb
    container_name: vto-db
    volumes:
      - vto-db-data:/var/lib/mysql/data
    env_file:
      - env
  cache:
    image: memcached
    container_name: vto-cache
volumes:
  vto-db-data: