version: '3.2'
services:
  web:
    build: .
    container_name: vto-web
    restart: always
    ports:
      - "80:80"
    links:
      - db
      - cache
    env_file:
      - env
    volumes:
      - ./web:/var/www/html
  db:
    image: lsioarmhf/mariadb-aarch64
    container_name: vto-db
    restart: always
    volumes:
      - vto-db-data:/var/lib/mysql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - ./backup:/backup
    env_file:
      - env
  cache:
    image: memcached
    container_name: vto-cache
    restart: always
volumes:
  vto-db-data: